host ?= 0.0.0.0
port ?= 8000
lint-dir ?= .

.PHONY: lint
lint:
	ruff check $(lint-dir) --fix ; ruff format $(lint-dir)

.PHONY: test
test:
	pytest .

.PHONY: serve
serve:
	uvicorn app:app --host $(host) --port $(port) --reload

.PHONY: build
build:
	docker build . --tag {{service_name}}

.PHONY: run
run:
	docker run -d -p $(port):$(port) --name {{service_name}} {{service_name}}

.PHONY: init
init:
	pyenv local {{python_version}}
	poetry install
